import { test } from "node:test";
import assert from "node:assert/strict";
import {
  acmeAioCapability,
  acmeFilesCapability,
  acmeMathCapability,
  acmePathsCapability,
  acmePlatformCapability,
  acmeVectorsCapability,
  artifactText,
  compilePython,
  strCarrier,
} from "./helpers/python-session.mjs";
import { createPythonTargetCapability } from "../dist/index.js";

test("provider free-function call lowers via from-import row metadata", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { readText } from "@acme/files";

export function load(path: string): string {
  return readText(path);
}
`,
    },
    capabilities: [acmeFilesCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "from acme_files import read_text",
    "",
    "",
    "def load(path: str) -> str:",
    "    return read_text(path)",
    "",
  ].join("\n"));
});

test("provider module-style call lowers to module attribute access", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { add } from "@acme/math";
import type { int32 } from "@tsonic/core/types.js";

export function total(a: int32, b: int32): int32 {
  return add(a, b);
}
`,
    },
    capabilities: [acmeMathCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /^import acme_math$/mu);
  assert.match(text, /return acme_math\.add\(a, b\)/u);
});

test("provider constructor and property lower through selected rows", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { Env } from "@acme/platform";

export function home(): string {
  const env = new Env();
  return env.homeDir;
}
`,
    },
    capabilities: [acmePlatformCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /from acme_platform import Env/u);
  assert.match(text, /env = Env\(\)/u);
  assert.match(text, /return env\.home_dir/u);
});

test("provider indexer lowers to subscript access", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { Vector } from "@acme/vectors";
import type { int32 } from "@tsonic/core/types.js";

export function first(): int32 {
  const vec = new Vector(1, 2);
  const index: int32 = 0;
  return vec[index];
}
`,
    },
    capabilities: [acmeVectorsCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /vec = Vector\(1, 2\)/u);
  assert.match(text, /return vec\[index\]/u);
});

test("stdlib-style class rows lower: constructor, property, method, static attribute", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { FilePath } from "@acme/paths";

export function rename(path: string, ext: string): string {
  const file = new FilePath(path);
  const next = file.withSuffix(ext);
  return next.suffix + FilePath.sep;
}
`,
    },
    capabilities: [acmePathsCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /from acme_paths import FilePath/u);
  assert.match(text, /file = FilePath\(path\)/u);
  assert.match(text, /next = file\.with_suffix\(ext\)/u);
  assert.match(text, /return next\.suffix \+ FilePath\.sep/u);
});

test("async provider rows lower only as await operands", () => {
  const awaited = compilePython({
    files: {
      "index.ts": `
import { fetchText } from "@acme/aio";

export async function load(key: string): Promise<string> {
  const body: string = await fetchText(key);
  return body;
}
`,
    },
    capabilities: [acmeAioCapability()],
  });
  assert.deepEqual(awaited.result.diagnostics, []);
  const text = artifactText(awaited.result, "src/tsonic_generated/index.py");
  assert.match(text, /from acme_aio import fetch_text/u);
  assert.match(text, /async def load\(key: str\) -> str:/u);
  assert.match(text, /body: str = await fetch_text\(key\)/u);

  const unawaited = compilePython({
    files: {
      "index.ts": `
import { fetchText } from "@acme/aio";

export async function load(key: string): Promise<string> {
  const pending = fetchText(key);
  return pending;
}
`,
    },
    capabilities: [acmeAioCapability()],
  });
  assert.equal(unawaited.result.artifacts.length, 0);
  assert.ok(unawaited.result.diagnostics.length > 0);
});

test("provider dependencies become pyproject dependencies", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { readText } from "@acme/files";
import { add } from "@acme/math";
import type { int32 } from "@tsonic/core/types.js";

export function use(path: string, a: int32): string {
  const text: string = readText(path);
  const count: int32 = add(a, a);
  if (count > 0) {
    return text;
  }
  return "";
}
`,
    },
    capabilities: [acmeFilesCapability(), acmeMathCapability()],
  });

  assert.deepEqual(result.diagnostics, []);
  const pyproject = artifactText(result, "pyproject.toml");
  assert.ok(pyproject.includes([
    "dependencies = [",
    '    "acme-files",',
    '    "acme-math",',
    "]",
  ].join("\n")));
});

test("provider exports without operation rows fail closed", () => {
  const unmappedPackage = createPythonTargetCapability({
    id: "acme-unmapped",
    displayName: "Unmapped fake package",
    version: "0.0.1",
    modules: [{
      moduleSpecifier: "@acme/unmapped",
      providerModuleId: "acme.unmapped",
      exports: [{
        id: "@acme/unmapped::mystery",
        name: "mystery",
        kind: "function",
        signatures: [{
          id: "@acme/unmapped::mystery()",
          name: "mystery",
          parameters: [],
          returnType: { kind: "string" },
        }],
      }],
    }],
    operations: [],
    dependencies: [{ name: "acme-unmapped" }],
  });

  const { result } = compilePython({
    files: {
      "index.ts": `
import { mystery } from "@acme/unmapped";

export function probe(): string {
  return mystery();
}
`,
    },
    capabilities: [unmappedPackage],
  });

  assert.equal(result.artifacts.length, 0);
  assert.ok(result.diagnostics.length > 0);
  assert.ok(result.diagnostics.every((diagnostic) => diagnostic.category === "error"));
});

test("str carrier constant matches the provider row contract", () => {
  assert.deepEqual(strCarrier, { kind: "target-named", id: "python.str" });
});

function packageDefinition(overrides) {
  return {
    id: "acme-bad",
    displayName: "Bad fake package",
    version: "0.0.1",
    modules: [{
      moduleSpecifier: "@acme/bad",
      providerModuleId: "acme.bad",
      exports: [{
        id: "@acme/bad::thing",
        name: "thing",
        kind: "function",
        signatures: [{
          id: "@acme/bad::thing()",
          name: "thing",
          parameters: [],
          returnType: { kind: "string" },
        }],
      }],
    }],
    operations: [],
    dependencies: [],
    targetIdentities: { "@acme/bad::thing": "acme.bad.Thing" },
    ...overrides,
  };
}

const validRow = {
  exportId: "@acme/bad::thing",
  operationKind: "method",
  target: { form: "call", import: { style: "from", module: "acme_bad", name: "thing" } },
  resultCarrier: strCarrier,
};

test("target capability creation rejects duplicate operation rows", () => {
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({ operations: [validRow, { ...validRow }] })),
    /duplicate operation row/u,
  );
});

test("target capability creation rejects invalid Python import and member names", () => {
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, target: { form: "call", import: { style: "from", module: "acme bad", name: "thing" } } }],
    })),
    /invalid Python module/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, target: { form: "call", import: { style: "from", module: "acme_bad", name: "not a name" } } }],
    })),
    /invalid Python import name/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, operationKind: "property", receiverTypeId: "acme.bad.Thing", target: { form: "property", name: "class" } }],
    })),
    /invalid Python member name/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, target: { form: "static-attribute", import: { style: "module", module: "acme_bad" }, name: "0bad" } }],
    })),
    /invalid Python attribute name/u,
  );
});

test("target capability creation rejects empty module identities and missing carriers", () => {
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      modules: [{ moduleSpecifier: "", providerModuleId: "acme.bad", exports: [] }],
    })),
    /module specifiers must be non-empty/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      modules: [{ moduleSpecifier: "@acme/bad", providerModuleId: "", exports: [] }],
    })),
    /provider module ids must be non-empty/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, resultCarrier: undefined }],
    })),
    /missing a result carrier/u,
  );
});

test("provider metadata fails at creation for structural inconsistencies", () => {
  const goodModule = {
    moduleSpecifier: "@acme/bad",
    providerModuleId: "acme.bad",
    exports: [{
      id: "@acme/bad::thing",
      name: "thing",
      kind: "function",
      signatures: [{ id: "@acme/bad::thing()", name: "thing", parameters: [], returnType: { kind: "string" } }],
    }],
  };
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      modules: [goodModule, { ...goodModule, providerModuleId: "acme.other" }],
    })),
    /duplicate module specifier/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      modules: [goodModule, { ...goodModule, moduleSpecifier: "@acme/other" }],
    })),
    /duplicate provider module id|duplicate export id/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, exportId: "@acme/bad::ghost" }],
    })),
    /undeclared export/u,
  );
});

test("row identities must prove against the declaration model", () => {
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, memberId: "@acme/bad::thing.ghost" }],
    })),
    /undeclared member '@acme\/bad::thing\.ghost'/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, signatureId: "@acme/bad::thing(ghost)" }],
    })),
    /undeclared signature '@acme\/bad::thing\(ghost\)'/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{
        ...validRow,
        operationKind: "property",
        receiverTypeId: "acme.bad.Unknown",
        target: { form: "property", name: "size" },
      }],
    })),
    /receiverTypeId 'acme\.bad\.Unknown', which is not a declared target identity/u,
  );
  // Declared identities pass: the export-level signature id validates.
  const valid = createPythonTargetCapability(packageDefinition({
    operations: [{ ...validRow, signatureId: "@acme/bad::thing()" }],
  }));
  assert.equal(valid.id, "acme-bad");
});

test("receiver-form rows require a receiverTypeId and isAsync is method-only", () => {
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, operationKind: "property", target: { form: "property", name: "size" } }],
    })),
    /requires a receiverTypeId/u,
  );
  assert.throws(
    () => createPythonTargetCapability(packageDefinition({
      operations: [{ ...validRow, operationKind: "property", isAsync: true, receiverTypeId: "acme.bad.Thing", target: { form: "property", name: "size" } }],
    })),
    /isAsync is supported only on method operations/u,
  );
});

test("dotted provider modules are accepted; reserved segments are not member names", () => {
  const dotted = createPythonTargetCapability(packageDefinition({
    operations: [{
      ...validRow,
      target: { form: "call", import: { style: "module", module: "acme_bad.sub_mod", name: "thing" } },
    }],
  }));
  assert.equal(dotted.id, "acme-bad");
});
