import { test } from "node:test";
import assert from "node:assert/strict";
import { createPythonBackend, pythonModuleNameForFile } from "../dist/index.js";
import { fakeCompileInput, fakeSourceFile } from "./helpers/fake-compile-input.mjs";

const backendContext = {
  project: { entryPoint: "src/index.ts", targets: [] },
  target: { id: "python", options: {} },
};

function artifactText(result, path) {
  const artifact = result.artifacts.find((candidate) => candidate.path === path);
  assert.ok(artifact, `expected artifact ${path}; got ${result.artifacts.map((a) => a.path).join(", ")}`);
  return artifact.text;
}

test("empty project emits a deterministic pyproject and package files", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({ sourceFiles: [] }));

  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.artifacts.map((artifact) => artifact.path), [
    "pyproject.toml",
    "src/tsonic_generated/__init__.py",
  ]);
  assert.equal(artifactText(result, "pyproject.toml"), [
    "[project]",
    'name = "tsonic_generated"',
    'version = "0.1.0"',
    'requires-python = ">=3.12"',
    "dependencies = []",
    "",
    "[tool.ruff]",
    'target-version = "py312"',
    "",
    "[tool.pytest.ini_options]",
    'testpaths = ["tests"]',
    "",
  ].join("\n"));
  assert.equal(
    artifactText(result, "src/tsonic_generated/__init__.py"),
    "# Generated by the Tsonic Python target. Do not edit.\n",
  );
  const [pyproject, initFile] = result.artifacts;
  assert.equal(pyproject.kind, "project");
  assert.equal(initFile.kind, "source");
  assert.equal(initFile.language, "python");
});

test("empty source files lower to header-only python modules in sorted order", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    sourceFiles: [
      fakeSourceFile({ fileName: "src/zeta.ts" }),
      fakeSourceFile({ fileName: "src/alphaBeta.ts" }),
    ],
  }));

  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.artifacts.map((artifact) => artifact.path), [
    "pyproject.toml",
    "src/tsonic_generated/__init__.py",
    "src/tsonic_generated/alpha_beta.py",
    "src/tsonic_generated/zeta.py",
  ]);
  assert.equal(
    artifactText(result, "src/tsonic_generated/alpha_beta.py"),
    "# Generated by the Tsonic Python target. Do not edit.\n",
  );
});

test("package name option controls generated package layout", () => {
  const target = { id: "python", options: { packageName: "acme_app", pythonVersion: "3.13" } };
  const backend = createPythonBackend({ ...backendContext, target });
  const result = backend.compile(fakeCompileInput({ target, sourceFiles: [] }));

  assert.deepEqual(result.diagnostics, []);
  assert.ok(result.artifacts.some((artifact) => artifact.path === "src/acme_app/__init__.py"));
  assert.match(artifactText(result, "pyproject.toml"), /name = "acme_app"/u);
  assert.match(artifactText(result, "pyproject.toml"), /requires-python = ">=3\.13"/u);
  assert.match(artifactText(result, "pyproject.toml"), /target-version = "py313"/u);
});

test("python-package runtime references become pyproject dependencies", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    runtimeReferences: [
      { kind: "python-package", include: "python-js", version: "0.0.1" },
      { kind: "python-package", include: "acme-vectors" },
    ],
  }));

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "pyproject.toml").includes([
    "dependencies = [",
    '    "acme-vectors",',
    '    "python-js==0.0.1",',
    "]",
  ].join("\n")), true);
});

test("unknown runtime reference kinds fail closed with zero artifacts", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    runtimeReferences: [{ kind: "cargo-path", include: "../rust-runtime" }],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "PYTHON_UNSUPPORTED_RUNTIME_REFERENCE");
  assert.ok(result.diagnostics[0].evidence.includes("runtime.reference.kind=cargo-path"));
});

test("malformed python-package names and versions fail closed", () => {
  const backend = createPythonBackend(backendContext);
  const badName = backend.compile(fakeCompileInput({
    runtimeReferences: [{ kind: "python-package", include: 'bad name"]\n[evil' }],
  }));
  assert.equal(badName.artifacts.length, 0);
  assert.equal(badName.diagnostics.length, 1);
  assert.equal(badName.diagnostics[0].code, "PYTHON_UNSUPPORTED_RUNTIME_REFERENCE");

  const badVersion = backend.compile(fakeCompileInput({
    runtimeReferences: [{ kind: "python-package", include: "python-js", version: '1.0"; rm -rf' }],
  }));
  assert.equal(badVersion.artifacts.length, 0);
  assert.equal(badVersion.diagnostics.length, 1);
  assert.equal(badVersion.diagnostics[0].code, "PYTHON_UNSUPPORTED_RUNTIME_REFERENCE");
});

test("conflicting duplicate python-package references fail closed", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    runtimeReferences: [
      { kind: "python-package", include: "python-js", version: "0.0.1" },
      { kind: "python-package", include: "python-js", version: "0.0.2" },
    ],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "PYTHON_UNSUPPORTED_RUNTIME_REFERENCE");
});

test("source files that cannot become python modules fail closed", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    sourceFiles: [fakeSourceFile({ fileName: "src/match.ts" })],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "PYTHON_MODULE_NAME");
});

test("module name collisions fail closed", () => {
  const backend = createPythonBackend(backendContext);
  const result = backend.compile(fakeCompileInput({
    sourceFiles: [
      fakeSourceFile({ fileName: "src/myApp.ts" }),
      fakeSourceFile({ fileName: "src/my_app.ts" }),
    ],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "PYTHON_MODULE_NAME");
  assert.match(result.diagnostics[0].message, /both map to Python module 'my_app'/u);
});

test("script output without a proven main entry fails closed", () => {
  const target = { id: "python", options: { outputType: "script" } };
  const backend = createPythonBackend({ ...backendContext, target });
  const result = backend.compile(fakeCompileInput({
    target,
    sourceFiles: [fakeSourceFile({ fileName: "src/index.ts" })],
  }));

  assert.equal(result.artifacts.length, 0);
  assert.equal(result.diagnostics.length, 1);
  assert.equal(result.diagnostics[0].code, "PYTHON_MISSING_ENTRYPOINT");
});

test("module names derive deterministically from file names", () => {
  assert.equal(pythonModuleNameForFile("src/index.ts"), "index");
  assert.equal(pythonModuleNameForFile("src/myApp.ts"), "my_app");
  assert.equal(pythonModuleNameForFile("src/data-utils.ts"), "data_utils");
  assert.equal(pythonModuleNameForFile("src/match.ts"), undefined);
  assert.equal(pythonModuleNameForFile("src/__init__.ts"), undefined);
  assert.equal(pythonModuleNameForFile("src/__main__.ts"), undefined);
});
