import { test } from "node:test";
import assert from "node:assert/strict";
import {
  acmeFilesPackage,
  acmeMathPackage,
  acmePlatformPackage,
  acmeVectorsPackage,
  artifactText,
  compilePython,
  strCarrier,
} from "./helpers/python-session.mjs";
import { createPythonProviderPackage } from "../dist/index.js";

test("provider free-function call lowers via from-import row metadata", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { readText } from "@acme/files";

export function load(path: string): string {
  return readText(path);
}
`,
    },
    packages: [acmeFilesPackage()],
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "from acme_files import read_text",
    "",
    "",
    "def load(path: str) -> str:",
    "    return read_text(path)",
    "",
  ].join("\n"));
});

test("provider module-style call lowers to module attribute access", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { add } from "@acme/math";
import type { int32 } from "@tsonic/core/types.js";

export function total(a: int32, b: int32): int32 {
  return add(a, b);
}
`,
    },
    packages: [acmeMathPackage()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /^import acme_math$/mu);
  assert.match(text, /return acme_math\.add\(a, b\)/u);
});

test("provider constructor and property lower through selected rows", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { Env } from "@acme/platform";

export function home(): string {
  const env = new Env();
  return env.homeDir;
}
`,
    },
    packages: [acmePlatformPackage()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /from acme_platform import Env/u);
  assert.match(text, /env = Env\(\)/u);
  assert.match(text, /return env\.home_dir/u);
});

test("provider indexer lowers to subscript access", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { Vector } from "@acme/vectors";
import type { int32 } from "@tsonic/core/types.js";

export function first(): int32 {
  const vec = new Vector(1, 2);
  const index: int32 = 0;
  return vec[index];
}
`,
    },
    packages: [acmeVectorsPackage()],
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /vec = Vector\(1, 2\)/u);
  assert.match(text, /return vec\[index\]/u);
});

test("provider dependencies become pyproject dependencies", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import { readText } from "@acme/files";
import { add } from "@acme/math";
import type { int32 } from "@tsonic/core/types.js";

export function use(path: string, a: int32): string {
  const text: string = readText(path);
  const count: int32 = add(a, a);
  if (count > 0) {
    return text;
  }
  return "";
}
`,
    },
    packages: [acmeFilesPackage(), acmeMathPackage()],
  });

  assert.deepEqual(result.diagnostics, []);
  const pyproject = artifactText(result, "pyproject.toml");
  assert.ok(pyproject.includes([
    "dependencies = [",
    '    "acme-files",',
    '    "acme-math",',
    "]",
  ].join("\n")));
});

test("provider exports without operation rows fail closed", () => {
  const unmappedPackage = createPythonProviderPackage({
    id: "acme-unmapped",
    displayName: "Unmapped fake package",
    version: "0.0.1",
    modules: [{
      moduleSpecifier: "@acme/unmapped",
      providerModuleId: "acme.unmapped",
      exports: [{
        id: "@acme/unmapped::mystery",
        name: "mystery",
        kind: "function",
        signatures: [{
          id: "@acme/unmapped::mystery()",
          name: "mystery",
          parameters: [],
          returnType: { kind: "string" },
        }],
      }],
    }],
    operations: [],
    dependencies: [{ name: "acme-unmapped" }],
  });

  const { result } = compilePython({
    files: {
      "index.ts": `
import { mystery } from "@acme/unmapped";

export function probe(): string {
  return mystery();
}
`,
    },
    packages: [unmappedPackage],
  });

  assert.equal(result.artifacts.length, 0);
  assert.ok(result.diagnostics.length > 0);
  assert.ok(result.diagnostics.every((diagnostic) => diagnostic.category === "error"));
});

test("str carrier constant matches the provider row contract", () => {
  assert.deepEqual(strCarrier, { kind: "target-named", id: "python.str" });
});
