import { test } from "node:test";
import assert from "node:assert/strict";
import {
  createPythonModule,
  escapePythonString,
  printPythonExpression,
  printPythonModule,
  printPythonStatement,
} from "../dist/index.js";

test("empty module prints the generated header with a trailing newline", () => {
  assert.equal(
    printPythonModule(createPythonModule([])),
    "# Generated by the Tsonic Python target. Do not edit.\n",
  );
});

test("imports and a function definition print black-style", () => {
  const module = createPythonModule([
    { kind: "import", module: "torch" },
    { kind: "from-import", module: "pathlib", names: [{ name: "Path" }] },
    {
      kind: "function-def",
      name: "add",
      params: [
        { name: "a", annotation: { kind: "name", name: "int" } },
        { name: "b", annotation: { kind: "name", name: "int" } },
      ],
      returns: { kind: "name", name: "int" },
      body: [{ kind: "return", expression: { kind: "name", name: "a" } }],
    },
  ]);

  assert.equal(printPythonModule(module), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "import torch",
    "from pathlib import Path",
    "",
    "",
    "def add(a: int, b: int) -> int:",
    "    return a",
    "",
  ].join("\n"));
});

test("async functions, aliases, and calls print deterministically", () => {
  assert.equal(
    printPythonStatement({ kind: "import", module: "numpy", alias: "np" }),
    "import numpy as np",
  );
  assert.equal(
    printPythonStatement({
      kind: "from-import",
      module: "acme_files",
      names: [{ name: "read_text", alias: "rt" }],
    }),
    "from acme_files import read_text as rt",
  );
  assert.equal(
    printPythonStatement({
      kind: "function-def",
      name: "load",
      isAsync: true,
      params: [{ name: "path", annotation: { kind: "name", name: "str" } }],
      returns: { kind: "name", name: "str" },
      body: [{ kind: "pass" }],
    }),
    ["async def load(path: str) -> str:", "    pass"].join("\n"),
  );
  assert.equal(
    printPythonExpression({
      kind: "call",
      callee: { kind: "attribute", value: { kind: "name", name: "torch" }, name: "empty_like" },
      args: [{ kind: "name", name: "x" }],
    }),
    "torch.empty_like(x)",
  );
});

test("literals print deterministically", () => {
  assert.equal(printPythonExpression({ kind: "bool-literal", value: true }), "True");
  assert.equal(printPythonExpression({ kind: "bool-literal", value: false }), "False");
  assert.equal(printPythonExpression({ kind: "none-literal" }), "None");
  assert.equal(printPythonExpression({ kind: "int-literal", text: "42" }), "42");
  assert.equal(printPythonExpression({ kind: "float-literal", text: "1.5" }), "1.5");
});

test("string escaping is deterministic and double-quoted", () => {
  assert.equal(escapePythonString("hello"), '"hello"');
  assert.equal(escapePythonString('say "hi"'), '"say \\"hi\\""');
  assert.equal(escapePythonString("line\nbreak\tand\\slash"), '"line\\nbreak\\tand\\\\slash"');
  assert.equal(escapePythonString(""), '"\\x01"');
  assert.equal(escapePythonString("héllo"), '"héllo"');
});

test("printer fails closed on unmodeled syntax", () => {
  assert.throws(
    () => printPythonExpression({ kind: "walrus" }),
    /Unsupported Python expression syntax reached printer: walrus/u,
  );
  assert.throws(
    () => printPythonStatement({ kind: "global-decl" }),
    /Unsupported Python statement syntax reached printer: global-decl/u,
  );
  assert.throws(
    () => printPythonStatement({ kind: "function-def", name: "empty", params: [], body: [] }),
    /Unsupported Python statement syntax reached printer/u,
  );
});
