import { test } from "node:test";
import assert from "node:assert/strict";
import { artifactText, compilePython } from "./helpers/python-session.mjs";

test("primitive function lowers to exact fact-backed Python", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function add(a: int32, b: int32): int32 {
  return a + b;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "def add(a: int, b: int) -> int:",
    "    return a + b",
    "",
  ].join("\n"));
});

test("source names are preserved verbatim, never PEP8-renamed", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function addTwice(firstValue: int32, secondValue: int32): int32 {
  const partialSum: int32 = firstValue + secondValue;
  return partialSum + partialSum;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /def addTwice\(firstValue: int, secondValue: int\) -> int:/u);
  assert.match(text, /partialSum: int = firstValue \+ secondValue/u);
  assert.doesNotMatch(text, /add_twice|first_value/u);
});

test("if/elif/else and comparison operators lower deterministically", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function classify(value: int32): int32 {
  if (value < 0) {
    return -1;
  } else if (value === 0) {
    return 0;
  } else {
    return 1;
  }
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "def classify(value: int) -> int:",
    "    if value < 0:",
    "        return -1",
    "    elif value == 0:",
    "        return 0",
    "    else:",
    "        return 1",
    "",
  ].join("\n"));
});

test("while loops, locals, and arithmetic lower with integer division", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function halveDown(start: int32): int32 {
  let current: int32 = start;
  while (current > 1) {
    current = current / 2;
  }
  return current;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /while current > 1:/u);
  assert.match(text, /current = _tsonic_int_div\(current, 2\)/u);
});

test("integer division and remainder lower to truncating helpers", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function quotRem(a: int32, b: int32): int32 {
  const quot: int32 = a / b;
  const rem: int32 = a % b;
  return quot + rem;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "def _tsonic_int_div(a: int, b: int) -> int:",
    "    q: int = a // b",
    "    if q < 0 and q * b != a:",
    "        q = q + 1",
    "    return q",
    "",
    "",
    "def _tsonic_int_rem(a: int, b: int) -> int:",
    "    return a - _tsonic_int_div(a, b) * b",
    "",
    "",
    "def quotRem(a: int, b: int) -> int:",
    "    quot: int = _tsonic_int_div(a, b)",
    "    rem: int = _tsonic_int_rem(a, b)",
    "    return quot + rem",
    "",
  ].join("\n"));
});

test("float remainder lowers to math.fmod with a collected import", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { float64 } from "@tsonic/core/types.js";

export function wrap(a: float64, b: float64): float64 {
  return a % b;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /^import math$/mu);
  assert.match(text, /return math\.fmod\(a, b\)/u);
});

test("source functions in the generated-helper namespace fail closed", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function _tsonic_int_div(a: int32, b: int32): int32 {
  return a;
}
`,
    },
  });

  assert.equal(result.artifacts.length, 0);
  assert.ok(result.diagnostics.length > 0);
});

test("boolean logic lowers to and/or/not", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
export function decide(ready: boolean, enabled: boolean): boolean {
  return ready && (enabled || !ready);
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  assert.match(
    artifactText(result, "src/tsonic_generated/index.py"),
    /return ready and \(enabled or not ready\)/u,
  );
});

test("string concat and equality lower through string facts", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
export function greet(name: string, formal: boolean): string {
  if (name === "world" || formal) {
    return "hello, " + name;
  }
  return name;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /if name == "world" or formal:/u);
  assert.match(text, /return "hello, " \+ name/u);
});

test("dense list lane: literal, index read/write, len, append, for-of", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function sumAll(): int32 {
  const values: int32[] = [1, 2, 3];
  values.push(4);
  values[0] = values[0] + values.length;
  let total: int32 = 0;
  for (const value of values) {
    total = total + value;
  }
  return total;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(artifactText(result, "src/tsonic_generated/index.py"), [
    "# Generated by the Tsonic Python target. Do not edit.",
    "",
    "def sumAll() -> int:",
    "    values: list[int] = [1, 2, 3]",
    "    values.append(4)",
    "    values[0] = values[0] + len(values)",
    "    total: int = 0",
    "    for value in values:",
    "        total = total + value",
    "    return total",
    "",
  ].join("\n"));
});

test("float carriers lower to float annotations and literals", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { float64 } from "@tsonic/core/types.js";

export function scale(value: float64): float64 {
  return value * 2.5;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /def scale\(value: float\) -> float:/u);
  assert.match(text, /return value \* 2\.5/u);
});

test("cross-module project imports lower to package-relative imports", () => {
  const { result } = compilePython({
    files: {
      "util.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function double(value: int32): int32 {
  return value + value;
}
`,
      "index.ts": `
import { double } from "./util.js";
import type { int32 } from "@tsonic/core/types.js";

export function quadruple(value: int32): int32 {
  return double(double(value));
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /from \.util import double/u);
  assert.match(text, /return double\(double\(value\)\)/u);
  assert.match(artifactText(result, "src/tsonic_generated/util.py"), /def double\(value: int\) -> int:/u);
});

test("reserved local names mangle deterministically with a trailing underscore", () => {
  const { result } = compilePython({
    files: {
      "index.ts": `
import type { int32 } from "@tsonic/core/types.js";

export function pick(match: int32): int32 {
  const from: int32 = match + 1;
  return from;
}
`,
    },
  });

  assert.deepEqual(result.diagnostics, []);
  const text = artifactText(result, "src/tsonic_generated/index.py");
  assert.match(text, /def pick\(match_: int\) -> int:/u);
  assert.match(text, /from_: int = match_ \+ 1/u);
  assert.match(text, /return from_/u);
});
