// Structured Python output model. The printer is the only component that
// turns these nodes into text; the planner never concatenates Python source.

export type PythonExpression =
  | { readonly kind: "int-literal"; readonly text: string }
  | { readonly kind: "float-literal"; readonly text: string }
  | { readonly kind: "bool-literal"; readonly value: boolean }
  | { readonly kind: "string-literal"; readonly value: string }
  | { readonly kind: "none-literal" }
  | { readonly kind: "name"; readonly name: string }
  | { readonly kind: "attribute"; readonly value: PythonExpression; readonly name: string }
  | { readonly kind: "call"; readonly callee: PythonExpression; readonly args: readonly PythonExpression[] };

export type PythonTypeAnnotation =
  | { readonly kind: "name"; readonly name: string }
  | { readonly kind: "none" };

export interface PythonParameter {
  readonly name: string;
  readonly annotation?: PythonTypeAnnotation;
}

export interface PythonImportedName {
  readonly name: string;
  readonly alias?: string;
}

export type PythonStatement =
  | { readonly kind: "import"; readonly module: string; readonly alias?: string }
  | { readonly kind: "from-import"; readonly module: string; readonly names: readonly PythonImportedName[] }
  | { readonly kind: "pass" }
  | { readonly kind: "expr"; readonly expression: PythonExpression }
  | { readonly kind: "return"; readonly expression?: PythonExpression }
  | {
      readonly kind: "assign";
      readonly targetName: string;
      readonly annotation?: PythonTypeAnnotation;
      readonly value: PythonExpression;
    }
  | {
      readonly kind: "function-def";
      readonly name: string;
      readonly params: readonly PythonParameter[];
      readonly returns?: PythonTypeAnnotation;
      readonly body: readonly PythonStatement[];
      readonly isAsync?: boolean;
    };

export interface PythonModuleModel {
  readonly headerComment: string;
  readonly statements: readonly PythonStatement[];
}

export const pythonGeneratedHeaderComment = "Generated by the Tsonic Python target. Do not edit.";

export function createPythonModule(statements: readonly PythonStatement[]): PythonModuleModel {
  return { headerComment: pythonGeneratedHeaderComment, statements };
}
